{% set name = "yt" %}
{% set version = "4.4.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0883a89c2543b436c3778f555edf253c71f252f744752dc1688f8524ad03b0b
  patches:
    - patches/force_cythonize.patch
    - patches/crossc-openmp.patch  # [linux]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - yt = yt.utilities.command_line:run_main
  skip: true  # [py<310]
  ignore_run_exports:
    - numpy
    - libcxx

requirements:
  build:
    #- {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - wheel
    - setuptools >=77.0.0
    - cython >=3.0.3
    - numpy {{ numpy }}
    - ewah-bool-utils >=1.2.0
  run:
    - python
    - cmyt >=1.1.2
    - ewah-bool-utils >=1.2.0
    - matplotlib-base >=3.5
    - more-itertools >=8.4
    - numpy >=1.21.3,<3  # [linux or win]
    - numpy >=1.21.3,<3,!=2.0.1  # [osx and arm64]
    - packaging >=20.9
    - pillow >=8.3.2
    - tomli-w >=0.4.0
    - tqdm >=3.4.0
    - unyt >=2.9.2
    - tomli >=1.2.3  # [py<311]
    - typing-extensions >=4.4.0  # [py<312]
    - _openmp_mutex  # [linux]
  run_constrained:
    # HDF5
    - h5py >=3.1.0  # [linux]
    # https://github.com/h5py/h5py/issues/2505
    - h5py >=3.1.0,!=3.12.0  # [win]
    # https://github.com/yt-project/yt/issues/5301
    - h5py >=3.1.0,!=3.15.0  # [osx]
    # netCDF4
    # https://github.com/Unidata/netcdf4-python/issues/1192
    - netCDF4 >=1.5.3,!=1.6.1
    # Fortran
    - f90nml >=1.1
    # cf-radial
    - xarray >=0.16.1
    - arm-pyart >=1.19.2
    # enzo, enzo-e
    - libconf>=1.0.1
    # fits
    - astropy >=4.0.1
    - regions >=0.7
    # http-stream, sdf
    - requests>=2.20.0
    # full
    - cartopy >=0.22.0
    - firefly >=3.2.0
    - glueviz >=0.13.3
    - ipython >=7.16.2
    - ipywidgets >=8.0.0
    - miniballcpp >=0.2.1
    - mpi4py >=3.0.3
    - pandas >=1.1.2
    - pooch >=0.7.0
    - pyaml >=17.10.0
    - pykdtree >=1.3.1
    - pyx >=0.15
    - scipy >=1.5.0
    # https://github.com/glue-viz/glue/issues/2263
    - glue-core !=1.2.4  # [py>310]
    - ratarmount >=0.8.1,<0.9.0  # [win or osx]

test:
  #source_files:
  #  - yt/tests
  imports:
    - yt
  commands:
    - pip check
    - yt --help
    # Ignore test file that imports nose, which uses imp, which was removed in python 3.12
    #- pytest -v  # [py<312]
    #- pytest -v --ignore=yt/tests/test_funcs.py  # [py>=312]
    - pytest --pyargs yt.tests
  requires:
    - pip
    - pytest
    - nose

about:
  home: https://yt-project.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: Analysis and visualization toolkit for volumetric data
  description: |
    yt is a community-developed analysis and visualization toolkit for
    volumetric data. yt has been applied mostly to astrophysical simulation
    data, but it can be applied to many different types of data including
    seismology, radio telescope data, weather simulations, and nuclear
  dev_url: https://github.com/yt-project/yt
  doc_url: https://yt-project.org/doc

extra:
  recipe-maintainers:
    - ngoldbaum
    - munkm
