{% set version = "4.0.1" %}

package:
  name: yt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/y/yt/yt-{{ version }}.tar.gz
  sha256: 6219cbf971871320a13679a57722c0363e50db5e6d4d64ea9d197461b2a7f70f

build:
  number: 0
  entry_points:
    - yt = yt.utilities.command_line:run_main

requirements:
  build:
    - {{ compiler('c') }}
    - llvm-openmp  # [osx]
  host:
    - python
    - pip
    - numpy
    - cython >=0.24.0
    - setuptools >=19.6
    - llvm-openmp  # [osx]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - h5py
    - sympy
    - matplotlib
    - ipython
    - llvm-openmp   # [osx]

test:
  imports:
    - yt
  commands:
    - pip check
    - yt --help
  requires:
    - pip
    - nose

about:
  home: http://yt-project.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: Analysis and visualization toolkit for volumetric data

extra:
  recipe-maintainers:
    - ngoldbaum
    - munkm
