{% set version = "4.4.0" %}

package:
  name: yt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/y/yt/yt-{{ version }}.tar.gz
  sha256: 0e15df9cb21abe582f8128bf0705a3bc0f4805f97efd6b4f883073703941c0d5
  patches:
    - patches/001_force_cythonize.patch

build:
  skip: True    # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - yt = yt.utilities.command_line:run_main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch  # [unix]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - numpy >=2.0.0
    - cython >=3.0.3
    - setuptools
    - wheel
    - ewah-bool-utils >=1.2.0
  run:
    - python
    - ewah-bool-utils >=1.2.0
    - matplotlib-base >=3.5
    - more-itertools >=8.4
    - numpy >=1.21.3,<3
    - numpy !=2.0.1  # [osx and arm64]
    - packaging >=20.9
    - pillow >=8.3.2
    - tomli >=1.2.3  # [py<311]
    - tomli-w >=0.4.0
    - tqdm >=3.4.0
    - unyt >=2.9.2
    - cmyt >=1.1.2
    - typing-extensions >=4.4.0  # [py<312]
    #- _openmp_mutex  # [linux]

test:
  source_files:
    - yt/tests
  imports:
    - yt
  commands:
    - pip check
    - yt --help
    # Ignore test file that imports nose, which uses imp, which was removed in python 3.12
    - pytest -v                                   # [py<312]
    - pytest -v --ignore=yt/tests/test_funcs.py   # [py>=312]
  requires:
    - pip
    - pytest
    - nose                                        # [py<312]

about:
  home: https://yt-project.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: Analysis and visualization toolkit for volumetric data
  description: |
    yt is a community-developed analysis and visualization toolkit for 
    volumetric data. yt has been applied mostly to astrophysical simulation 
    data, but it can be applied to many different types of data including 
    seismology, radio telescope data, weather simulations, and nuclear 
  dev_url: https://github.com/yt-project/yt/
  doc_url: https://yt-project.org/docs/dev/

extra:
  recipe-maintainers:
    - ngoldbaum
    - munkm
