{% set version = "3.4.1" %}
{% set sha256 = "a4cfc47fe21683e7a3b680c05fe2a25fb774ffda6e3939a35755e5bf64065895" %}

package:
  name: yt
  version: {{ version }}

source:
  fn: yt-{{ version }}.tar.gz
  url: http://yt-project.org/sdist/yt-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: python setup.py -q install --single-version-externally-managed --record=record.txt  # [not win]
  script: python setup.py -q install --single-version-externally-managed --record=record.txt  # [win]
  entry_points:
    - yt = yt.utilities.command_line:run_main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - numpy 1.11.*
    - cython >=0.24.0
    - setuptools >=19.6
  run:
    - setuptools
    - python
    - {{ pin_compatible('numpy') }}
    - h5py
    - sympy
    - matplotlib
    - ipython

test:
  requires:
    - nose
  commands:
    - yt -h
  imports:
    - yt

about:
  home: http://yt-project.org/
  license: BSD 3-clause
  summary: Analysis and visualization toolkit for volumetric data

extra:
    recipe-maintainers:
      - ngoldbaum
      - xarthisius
