{% set version = "3.4.1" %}
{% set sha256 = "a4cfc47fe21683e7a3b680c05fe2a25fb774ffda6e3939a35755e5bf64065895" %}

package:
  name: yt
  version: {{ version }}

source:
  fn: yt-{{ version }}.tar.gz
  url: http://yt-project.org/sdist/yt-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: env EMBREE_DIR=$PREFIX python setup.py -q install --single-version-externally-managed --record=record.txt  # [not win]
  script: python setup.py -q install --single-version-externally-managed --record=record.txt  # [win]
  entry_points:
    - yt = yt.utilities.command_line:run_main

requirements:
  build:
    - {{ compiler('c') }}
    - llvm-openmp   # [osx]
  host:
    - python
    - numpy 1.11.*
    - cython >=0.24.0
    - setuptools >=19.6
    - llvm-openmp   # [osx]
    # Removed for now.  Requires tbb, embree built from source.
    # - pyembree  # [linux]
  run:
    - setuptools
    - python
    - {{ pin_compatible('numpy') }}
    - h5py
    - sympy
    - matplotlib
    - ipython
    # Removed for now.  Requires tbb, embree built from source.
    #- pyembree  # [linux]
    # does not have run_exports (possibly should)
    - llvm-openmp   # [osx]

test:
  requires:
    - nose
  commands:
    - yt -h
  imports:
    - yt

about:
  home: http://yt-project.org/
  license: BSD 3-clause
  summary: Analysis and visualization toolkit for volumetric data

extra:
    recipe-maintainers:
      - ngoldbaum
      - xarthisius
