{% set version = "3.4.1" %}
{% set sha256 = "a4cfc47fe21683e7a3b680c05fe2a25fb774ffda6e3939a35755e5bf64065895" %}

package:
  name: yt
  version: {{ version }}

source:
  fn: yt-{{ version }}.tar.gz
  url: http://yt-project.org/sdist/yt-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: env EMBREE_DIR=$PREFIX {{ PYTHON }} setup.py -q install --single-version-externally-managed --record=record.txt  # [not win]
  script: {{ PYTHON }} setup.py -q install --single-version-externally-managed --record=record.txt  # [win]
  entry_points:
    - yt = yt.utilities.command_line:run_main

requirements:
  build:
    - {{ compiler('c') }}
    - llvm-openmp  # [osx]
  host:
    - python
    - numpy 1.11.*
    - cython >=0.24.0
    - setuptools >=19.6
    - llvm-openmp  # [osx]
    # Weird, Win python 2.7 gives:
    # Warning! ***HDF5 library version mismatched error***
    # Headers are 1.8.18, library is 1.8.20
    # - hdf5 1.8.18  # [win and py==27]
    # - hdf5 1.10.*  # [not win or py!=27]]
    - hdf5
    # Removed for now.  Requires tbb, embree built from source.
    # - pyembree   # [linux]
  run:
    - setuptools
    - python
    - {{ pin_compatible('numpy') }}
    - h5py
    # - hdf5 1.8.18  # [win and py==27]
    # - hdf5         # [not win or py!=27]]
    - sympy
    - matplotlib
    - ipython
    # Removed for now.  Requires tbb, embree built from source.
    #- pyembree  # [linux]
    # does not have run_exports (possibly should)
    - llvm-openmp   # [osx]

test:
  requires:
    - nose
  commands:
    - yt -h
  imports:
    - yt

about:
  home: http://yt-project.org/
  license: BSD 3-clause
  summary: Analysis and visualization toolkit for volumetric data

extra:
    recipe-maintainers:
      - ngoldbaum
      - xarthisius
