{% set version = "3.3.1" %}

package:
  name: yt
  version: {{ version }}

source:
  fn: yt-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/source/y/yt/yt-{{ version }}.tar.gz
  sha256: 01e3b3398d43b8eab698d55ba37ef3d701ea026b899c0940a1ee34b215e25a31

build:
  number: 1
  script: env EMBREE_DIR=$PREFIX python setup.py install --single-version-externally-managed --record=record.txt  # [not win]
  script: python setup.py install --single-version-externally-managed --record=record.txt  # [win]
  entry_points:
    - yt = yt.utilities.command_line:run_main

requirements:
  build:
    - python
    - numpy x.x
    - cython >=0.24.0
    - setuptools >=19.6
    - pyembree  # [not win]
  run:
    - setuptools
    - python
    - numpy x.x
    - h5py
    - sympy
    - matplotlib
    - ipython
    - pyembree  # [not win]

test:
  requires:
    - nose
  commands:
    - yt -h
  imports:
    - yt

about:
  home: http://yt-project.org/
  license: BSD 3-clause
  summary: Analysis and visualization toolkit for volumetric data

extra:
    recipe-maintainers:
      - ngoldbaum
      - xarthisius
