{% set version = "3.3.0" %}

package:
  name: yt
  version: {{ version }}

source:
  fn: yt-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/source/y/yt/yt-{{ version }}.tar.gz
  sha256: 537c67e85c8f5cc5530a1223a74d27eb7f11c459651903c3092c6a97b450d019

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - yt = yt.utilities.command_line:run_main

requirements:
  build:
    - python
    - numpy x.x
    - cython >=0.24.0
    - setuptools >=19.6
  run:
    - setuptools
    - python
    - numpy x.x
    - h5py
    - sympy
    - matplotlib
    - ipython

test:
  requires:
    - nose
  commands:
    - yt -h
  imports:
    - yt

about:
  home: http://yt-project.org/
  license: BSD 3-clause
  summary: Analysis and visualization toolkit for volumetric data

extra:
    recipe-maintainers:
      - ngoldbaum
      - xarthisius
