travis:
  secure:
    BINSTAR_TOKEN: YAAaqcdABL/LjKrnoAd0BL7aQM9Flh57axZQITWS/sc1Qt3+TNk/HW0HuUS+SAswVeIz1pF4h0B5j54kCS3p/LzRZ5OEYZZKQHr6nsQV7VneJv+e5Lwtzs7TZQ3SjNPf4Mk+nEhWkWz37h4uU4bC4wITVFLTNWr4h4R3UxMmobhRJGIiwUS+xJ5qM9XtMn7lVxjMVDePpeAAZa/3RI4LXj8PsvfPQCtteYM/U/Bqgx1QqiAn+6+57kmaDWq7eBRH+s5zlLLmkLiOTsVebNN7Hqi0gzLLwE63hHX+yl6awYknlmx8n6ohp+fZNXSW4etYl9yeKZNpfvtp5s9XS8heO27n4YFVrmy6MkjZnyl6WiX7XSc7iu4dOnQFIJYVLl7ASM9im2SoMRNZpSsyZfDhjTA0NYt66TmNDgEn6BGCLV5li8D96Ll5nqBU0drAV91Dlz9KRrAJqv6Q+i2h1ttMHbdOXT1nYHB4JRjbG+K0TcRfZVzIolO97YjmDmZW8eQXT3C0nlEhus8YXngyuLjw5mJ3qkSt9qukogvzk8rO6BAqIzw5Gb15U23c9rvAAB1yvxVLgNF++v7I8vpPuOGz1pu75uVgglHVtYswt8pWoqbU7uZ2HdNo4fSPWJVHLKc19Vr3cuyZ+rAfE7k33jT+1n1+GvCoyAxSsoqEnKXRURg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
